IOAS/Models/CrystalReportViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IOAS.Models
{
    public class CrystalReportViewModels
    {
    }
    public class ProposalRepotViewModels
    {
        [Required]
        [Display(Name = "From date")]
        public DateTime FromDate { get; set; }
        [Required]
        [Display(Name = "To date")]
        public DateTime ToDate { get; set; }
        [Required]
        [Display(Name = "Project type")]
        public int ProjecttypeId { get; set; }
        public string Proposalnumber { get; set; }
        public string PI { get; set; }
        public string ProposalTitle { get; set; }
        public string Department { get; set; }
        public DateTime InwardDate { get; set; }
        public int Durationofprojectyears { get; set; }
        public int Durationofprojectmonths { get; set; }
        public DateTime Crtd_TS { get; set; }
        public string keysearch { get; set; }

    }
}

IOAS/Controllers/CrystalReportController.cs
using CrystalDecisions.CrystalReports.Engine;
using IOAS.Infrastructure;
using IOAS.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IOAS.GenericServices;
namespace IOAS.Controllers
{
    
    public class CrystalReportController : Controller
    {
        // GET: CrystalReport
        [Authorize]
        [HttpGet]
        public ActionResult ProjectProposal()
        {
            ViewBag.projecttype = Common.getprojecttype();
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult ProjectProposal(ProposalRepotViewModels model)
        {
            ViewBag.projecttype = Common.getprojecttype();
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/CrystalReport"), "Proposalsponsored.rpt"));
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            ViewBag.report = CrystalReportService.Getproposal(model);
            rd.SetDataSource(ViewBag.report);
            rd.SetParameterValue("Fromdate", model.FromDate);
            rd.SetParameterValue("Todate", model.ToDate);
            if (model.ProjecttypeId == 1)
            {
                rd.SetParameterValue("heading", "SPONSORED PROJECT PROPOSALS");
            }
            else
            {
                rd.SetParameterValue("heading", "CONSULTANCY PROJECT PROPOSALS");
            }
            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            Response.AddHeader("Content-Disposition", "inline; filename=Proposal_Report.pdf");
            return File(stream, "application/pdf");
           
            
        }

        [Authorize]
        public ActionResult ProposalReport(ProposalRepotViewModels model)
        {
            ViewBag.projecttype = Common.getprojecttype();
            ReportDocument rd = new ReportDocument();
            rd.Load(Path.Combine(Server.MapPath("~/CrystalReport"), "Proposalsponsored.rpt"));
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            ViewBag.report = CrystalReportService.Getproposal(model);
            rd.SetDataSource(ViewBag.report);
            rd.SetParameterValue("Fromdate", model.FromDate);
            rd.SetParameterValue("Todate", model.ToDate);
            if (model.ProjecttypeId == 1)
            {
                rd.SetParameterValue("heading", "SPONSORED PROJECT PROPOSALS");
            }
            else
            {
                rd.SetParameterValue("heading", "CONSULTANCY PROJECT PROPOSALS");
            }
            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);
            Response.AddHeader("Content-Disposition", "inline; filename=Proposal_Report.pdf");
            return File(stream, "application/pdf");
        }
    }
}

IOAS/Views/CrystalReport/ProjectProposal.cshtml
@model IOAS.Models.ProposalRepotViewModels
@{
    ViewBag.Title = "ProjectProposal";
    Layout = "~/Views/Shared/_LayoutFluid.cshtml";
}

<div class="row hd-tt-bg" id="addnewpage">
    <div class="col-md-4">
        <h3>Sponsored/Consultancy Project Proposal</h3>
    </div>
</div>
<div class="row">
@using (Html.BeginForm("ProjectProposal", "CrystalReport", FormMethod.Post, new { @class = "", role = "form", @id = "formReport", enctype = "multipart/form-data" }))
{
    <div class="col-md-12">
        <div class="page-wrapper">
            <div class="white-bg">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group custom-form-group">
                            <label>From date</label>
                            @Html.EditorFor(M => M.FromDate, null, "FromDate", new { @class = "form-control", @id = "txtfromdate", @required = "required"})
                            <div class="txt-error txt-red"> @Html.ValidationMessageFor(M => M.FromDate)</div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group custom-form-group">
                            <label>To date</label>
                            @Html.EditorFor(M => M.ToDate,null, "ToDate", new { @class = "form-control", @id = "txttodate", @required = "required" })
                            <div class="txt-error txt-red"> @Html.ValidationMessageFor(M => M.ToDate)</div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group custom-form-group">
                            <label>Project type</label>
                            @Html.DropDownListFor(M => M.ProjecttypeId, new SelectList(ViewBag.projecttype, "codevalAbbr", "CodeValDetail"), "Select Project type", new { @id = "ddlprotype", @class = "form-control", @required = "required" })
                            <div class="txt-error txt-red"> @Html.ValidationMessageFor(M => M.ProjecttypeId)</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group custom-form-group">
                            <label>Key word</label>
                            @Html.TextBoxFor(M => M.keysearch, new { @class = "form-control", @id = "txtkeysearch",@placeholder= "PI Name /Proposal Title / Department/Proposal Number " })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center pd-tb-30">
                    <input type="submit" class="btn btn-primary mr10" value="View Report" id="btnreport" />
                    <a href="@Url.Action("Dashboard", "Home")" class="btn btn-default">Close</a>
                </div>
            </div>
        </div>
    </div>
}
</div>
<script>
    $('#btnreport').click(function (e) {
        e.preventDefault();
        var isValid = $('#formReport').valid();
        if (isValid) {
            var win = window.open('', '_blank');
            var url = "@Url.RouteUrl(new
            { Controller = "CrystalReport", Action = "ProposalReport" })?FromDate=" + $('#FromDate').val();
            win.location.href = url + "&ToDate=" + $('#ToDate').val()+ "&ProjecttypeId=" + $('#ddlprotype').val() + "&keysearch=" + $('#txtkeysearch').val();
        }
    });
</script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>